---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 10.100.1.188
    jenkins-agent-01:
      ansible_host: 10.100.1.187
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: srg
